name: test-11-slack-message-blocks

on: [push, issues]

jobs:
  slack-action:
    runs-on: ubuntu-20.04
    name: Test 11 [ubuntu-20.04]

    steps:
      - name: Send Slack Message (Blocks)
        uses: archive/github-actions-slack@update_message_with_blocks
        id: send-message
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C046J5U2RGC
          slack-blocks: >-
            [
              {
                "block_id": "text1",
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Building repo *product-service*"
                }
              },
              {
                "type": "divider"
              },
              {
                "block_id": "text2",
                "type": "context",
                "elements": [
                  {
                    "type": "image",
                    "image_url": "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/1200px-Flag_of_Sweden.svg.png",
                    "alt_text": "images"
                  },
                  {
                    "type": "plain_text",
                    "text": "Estimated time: 1 min"
                  }
                ]
              },
              {
                "type": "divider"
              }
            ]

      - name: Result from "Send Slack Message"
        run: echo '${{ steps.send-message.outputs.slack-result }}'
