name: test-5-slack-update-message

on: [push]

jobs:
  slack-action:
    #if: ${{ false }}
    runs-on: ubuntu-20.04
    name: Test 5 [ubuntu-20.04]

    steps:
      - name: Send Slack Message
        uses: archive/github-actions-slack@master
        id: send-message

        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C036UR2CRRR
          slack-text: Test 5 - Message to update

      - name: Send Slack Message Result
        run: echo 'Data - ${{ steps.send-message.outputs.slack-result }}'

      - name: Some step in between
        run: echo '...'

      - name: Send Slack Reaction To Message
        uses: archive/github-actions-slack@master
        with:
          slack-function: update-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: ${{ fromJson(steps.send-message.outputs.slack-result).response.channel }}
          slack-update-message-ts: ${{ fromJson(steps.send-message.outputs.slack-result).response.message.ts }}
          slack-update-message-text: Test 5.1 - Message to update - updated

      - name: Send Slack Reaction To Message Result
        run: echo 'Data - ${{ steps.send-message.outputs.slack-result }}'
